/* =========================================================
   Self hosts the two typefaces so nothing on this site, or in a
   mockup somebody opens straight off disk, reaches out to Google.

   Run once:  node tools/fonts.js
   Writes:    assets/fonts/*.woff2  and  css/fonts.css
   ========================================================= */

const fs = require("fs");
const path = require("path");
const https = require("https");

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "assets", "fonts");
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
           "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
const SRC = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700" +
            "&family=Plus+Jakarta+Sans:wght@700;800&display=swap";

const get = (url, binary) => new Promise((res, rej) => {
  https.get(url, { headers: { "User-Agent": UA } }, r => {
    if (r.statusCode >= 300 && r.statusCode < 400 && r.headers.location)
      return get(r.headers.location, binary).then(res, rej);
    if (r.statusCode !== 200) return rej(new Error(url + " -> " + r.statusCode));
    const chunks = [];
    r.on("data", c => chunks.push(c));
    r.on("end", () => res(binary ? Buffer.concat(chunks) : Buffer.concat(chunks).toString("utf8")));
  }).on("error", rej);
});

(async () => {
  fs.mkdirSync(OUT, { recursive: true });
  const css = await get(SRC, false);

  /* Google emits one @font-face per subset, each preceded by a comment
     naming it. Only latin is needed here. */
  const blocks = css.split("/*").slice(1)
    .map(b => ({ subset: b.slice(0, b.indexOf("*/")).trim(), body: b.slice(b.indexOf("*/") + 2) }))
    .filter(b => b.subset === "latin");

  const faces = [];
  for (const b of blocks) {
    const fam = (b.body.match(/font-family:\s*'([^']+)'/) || [])[1];
    const wt = (b.body.match(/font-weight:\s*(\d+)/) || [])[1];
    const url = (b.body.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    if (!fam || !wt || !url) continue;
    const file = `${fam.toLowerCase().replace(/\s+/g, "-")}-${wt}.woff2`;
    const buf = await get(url, true);
    fs.writeFileSync(path.join(OUT, file), buf);
    faces.push({ fam, wt, file, kb: Math.round(buf.length / 1024) });
    console.log(`  ${file.padEnd(30)} ${Math.round(buf.length / 1024)} KB`);
  }

  const out = `/* Self hosted. Generated by tools/fonts.js, do not edit by hand.
   Paths are relative to this file, which also makes them correct for
   the mockups, since both sit one level below the site root. */
${faces.map(f => `@font-face{
  font-family:"${f.fam}";
  font-style:normal;
  font-weight:${f.wt};
  font-display:swap;
  src:url("../assets/fonts/${f.file}") format("woff2");
}`).join("\n")}
`;
  fs.writeFileSync(path.join(ROOT, "css", "fonts.css"), out);
  console.log(`\n${faces.length} faces, css/fonts.css written`);
})();
